Repository offer-fe/Team_Price_Offer_FE, pull requests merged in 2022-01, with the labels that each got.

#3 📝 docs : PR, Issue 템플릿 수정
  .github/ISSUE_TEMPLATE/off_issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs

#7 🔧 config: typescript lint 설정
  .eslintrc.js
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
Labels: 🔧 config

#8 ♻️ refactor: base component 타입스크립트 적용 및 스토리북 리팩토리
  .storybook/main.js
  src/assets/images/no-image_product.png
  src/assets/images/no-image_user.png
  src/components/base/Avatar/index.tsx
  src/components/base/Avatar/styled.tsx
  src/components/base/Avatar/types.ts
  src/components/base/Image/index.tsx
  src/components/base/Image/styled.ts
  src/components/base/Image/types.ts
  src/data/constants/color.js
  src/data/constants/icon.js
  src/data/constants/images.js
  src/data/constants/index.js
  src/data/models/index.ts
  src/data/models/types.ts
  src/stories/components/base/Avatar.stories.tsx
  src/stories/components/base/Image.stories.tsx
  tsconfig.path.json
Labels: ♻️ refactor
